version: '3'
services:
 
  jboss:
 
    hostname: jboss
     
    build:
      context: .
      dockerfile: docker/jboss.dockerfile
     
    image: goodbytes.local
 
    ports:
        - "9990:9990"
        - "8585:8080"
        - "8787:8787"
     
    volumes:
      - ./deployment:/opt/jboss/wildfly/standalone/deployments/ 
      
      - ./configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      
      - ./configuration/iniciar.sh:/opt/jboss/wildfly/standalone/configuration/iniciar.sh 
      - ./configuration/wait-for-it.sh:/opt/jboss/wildfly/standalone/configuration/wait-for-it.sh
      
      - ./jdbc-oracle/ojdbc8.jar:/opt/jboss/wildfly/modules/system/layers/base/com/oracle/main/ojdbc8.jar
      - ./jdbc-oracle/module.xml:/opt/jboss/wildfly/modules/system/layers/base/com/oracle/main/module.xml
      
    links:
      - oraclebd
      
    container_name: jboss
   
    entrypoint: /opt/jboss/wildfly/standalone/configuration/iniciar.sh   
      
  oraclebd:
   
    hostname: oraclebd     
   
    image: sath89/oracle-12c 
    
    ports:
        - "1521:1521" 
        - "8080:8080"

    volumes:
      - ./oradata:/u01/app/oracle/ 
      
    container_name: oraclebd
    
 