version: '3'
services:
 
  jboss:
 
    hostname: jboss
     
    build:
      context: .
      dockerfile: docker/jboss.dockerfile
     
    image: goodbytes.local
 
    ports:
        - "9990:9990"
        - "8080:8080"
     
    volumes:
      - ./deployment:/opt/jboss/wildfly/standalone/deployments/
      - ./configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      
    links:
      - oraclebd
      
    container_name: jboss
      
  oraclebd:
    # pass a hostname to the container (optinal)
    hostname: oraclebd    
 
    # a name for easier reference
    image: sath89/oracle-12c

    # map host port 8080 to container port 80
    ports:
        - "1521:1521"
        - "8090:8090"
        
    container_name: oraclebd
    
 