version: '3'
services:
 
  jboss:
 
    hostname: jboss
     
    build:
      context: .
      dockerfile: docker/jboss.dockerfile
     
    image: goodbytes.local
 
    ports:
        - "9990:9990"
        - "8585:8080"
        - "8787:8787"
     
    volumes:
      - ./deployment:/opt/jboss/wildfly/standalone/deployments/ 
      - ./configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ./configuration/iniciar.sh:/opt/jboss/wildfly/standalone/configuration/iniciar.sh
      
    links:
      - oraclebd
      
    container_name: jboss
   
    entrypoint: /opt/jboss/wildfly/standalone/configuration/iniciar.sh   
      
  oraclebd:
    # pass a hostname to the container (optinal)
    hostname: oraclebd     
      
    # a name for easier reference
    image: sath89/oracle-12c

    # map host port 8080 to container port 80
    ports:
        - "1521:1521" 

    volumes:
      - ./oradata:/u01/app/oracle/ 
      
    container_name: oraclebd
    
 